### ISSUE TITLE
question about scale

### ISSUE THREAD

**Issue by johnren-code** [szymanowiczs/splatter-image#23]
I wonder why opacity_scale(0.001), xyz_scale(0.000001), scale_scale(0.001) of shapenet cars dataset is set to such value?

**Comment by johnren-code** [comment]
Another question, in the article, you mentioned using a camera transformation based on the relative pose of the first frame of the image, if I want to implement a predicted Gaussian parameter based on a single image and its camera pose, and render the resulting image under the same camera pose, i.e., train on a single image, would it be reasonable to use the corresponding camera pose information inside the dataset directly?

**Comment by johnren-code** [comment]
what's more, i also want to know how to determine the value of znear and zfar of other synthetic dataset.

**Comment by szymanowiczs** [comment]
Hi, 
- initialisation was tuned manually to have reasonable semi-transparent, camera-aligned shape at the start. It is possible other initialisation are better, this tuning wasn't a grid-search but instead a bit of trial and error. This initialisation is a good starting point but having bigger scales might work well too.
- If you train on a single image per object instance, the network will converge to a trivial `billboard' solution because there won't be any incentive for it to produce plausible 3D shapes. You can try it yourself by setting opt.imgs_per_obj=1.
- zfar and znear should be such that the full object is definitely within these bounds relative to the camera. A good rule of thumb is to use znear = distance to object - w and zfar = distance to object + w where w \approx 2.5 * max_object_size / 2 . Again, this is a good starting point and you might want to tweak them based on your experimental results.

**Comment by johnren-code** [comment]
Thank you for your answer!

When you mention distance to object do you mean the distance from the camera to the object in the world coordinate system? And how exactly are the dimensions of w and distance to object defined? As a rule of thumb, I set the znear and zfar to 0.01 and 10 respectively for the new dataset in the first experiment, do you think this is reasonable?
