### ISSUE TITLE
about sh_degree

### ISSUE THREAD

**Issue by johnren-code** [szymanowiczs/splatter-image#26]
I would like to know why sh_degree is set to only 1, can I try a larger value?

**Comment by johnren-code** [comment]
what's more, if I want to render a multi-channel image instead of an RGB image, how do I change the code?

**Comment by huoxingdawang** [comment]
In my opinion, if you want to render a multi-channel image, may be you should modify the 3DGS renderer, which is write in cuda.

Maybe like some segmentation work?
[gaussian-grouping](https://github.com/lkeab/gaussian-grouping)

**Comment by szymanowiczs** [comment]
For rendering features you would need to modify the rasterizer - I think there are some forks of the gaussian splatting repository that render features.

You can definitely try more spherical harmonics - it will work for a single image when the input camera is identity. Unfortunately rotating spherical harmonics of order more than 1 is a bit more involved so you would need to deal with that if you want to transform between reference frames (but if you have only one image you can just modify the camera poses so that the source camera is identity)
