### ISSUE TITLE
Question about gaussian prediction

### ISSUE THREAD

**Issue by Pixie8888** [szymanowiczs/splatter-image#28]
Dear author,

Thank you very much for sharing code! I have some question about gaussian prediction:

1. Does the network try to predict ground-truth depth for each foreground pixel? In other words, only the location of each gaussian close the ground truth depth can the rendering be good?
2. Why is the ```pos``` normalized in line 786 shown below?
<img width="838" alt="image" src="https://github.com/szymanowiczs/splatter-image/assets/72333326/4ba28219-c26e-4a8a-8710-620825ff7d6e">

**Comment by johnren-code** [comment]
Same quesion, have you conducted any experiments to validate your ideas?

**Comment by huoxingdawang** [comment]
Hello,
To my understant, `pos` is caclucated using `depth`:


https://github.com/szymanowiczs/splatter-image/blob/98b465731c3273bf8f42a747d1b6ce1a93faf3d6/scene/gaussian_predictor.py#L773

And in the `get_pos_from_network_output`, you can see that `depth` , which is between 0 to 1, is converted to the `pos` in the same units as the camera pose by `znear` and `zfar`:

https://github.com/szymanowiczs/splatter-image/blob/98b465731c3273bf8f42a747d1b6ce1a93faf3d6/scene/gaussian_predictor.py#L706

So, in my opinion, if the argument `znear` and `zfar` is not set correctly, the rendering will be bad.

Then for the line 786:

The line 782 to 784 added a new dim to the pos, so now the `pos` is `[x,y,z,1]` rather than `[x,y,z]` and this is because `source_cameras_view_to_world` in line 785 is a 4x4 rotation + translation matrix, there needs a extra `1`  to allow two matrices to be multiplied.

After the line 785, the `[x,y,z,1]` need to be coverted back to `[x,y,z]` . However, after multiplied, the `[x,y,z,1]` is  not `[x,y,z,1]`, it can be `[x,y,z,w]`  and `w` is not `1`, so `[x,y,z]` need to be `[x/w,y/w,z/w]` , it is not "normalized".

**Comment by Egolee0713** [comment]
@szymanowiczs  @huoxingdawang @Pixie8888  Hello, I have some question in line 785(pos = torch.bmm(pos, source_cameras_view_to_world) ) which convert pos_in_cam to pos_in_world. According to my understanding, it should pos @ source_cameras_view_to_world.T or source_cameras_view_to_world @ pos? I would be very grateful if I could receive your answer.

**Comment by szymanowiczs** [comment]
Hi @yongjingli - the cameras are in row major order, that is they assume that the position vectors are row vectors (N x 3). In this convention pos_world = torch.bmm(pos, source_cameras_view_to_world). See the readme for more information about the cameras, and you can find a .transpose() in the dataset files. Hope this helps to clarify it.

**Comment by szymanowiczs** [comment]
Hi @Pixie8888 @johnren-code @huoxingdawang. As @huoxingdawang points out, the [x, y, z, 1] are homogeneous coordinates. This way the points can be multiplied with 4x4 camera matrices to apply a rigid body transform to them. the division by the 4th coordinate un-homogenises them - moves back from homogeneous space to euclidean space.
