### ISSUE TITLE
why killed?

### ISSUE THREAD

**Issue by johnren-code** [szymanowiczs/splatter-image#30]
The training process will be killed in the half

**Comment by johnren-code** [comment]
If I understand correctly, the main reason for being killed is due to insufficient memory during the training process. I noticed that memory usage increases continuously at the beginning of training and stabilizes at around a certain value. What is the reason for this?

**Comment by szymanowiczs** [comment]
The dataset is being read into working memory - see the data loader where new images are appended to the dataset object attributes https://github.com/szymanowiczs/splatter-image/blob/98b465731c3273bf8f42a747d1b6ce1a93faf3d6/scene/co3d.py#L144C13-L145C1 
This is done so that data loading doesn't bottleneck training. 

It is possible that the entire dataset does not fit into RAM, depending on the machine you're using.

If this is an issue for you, you will need to modify the data loader so that the data is being read just for the current iteration - make sure to provide enough workers so that the training process does not become cpu-bottlenecked.

**Comment by johnren-code** [comment]
Yeah, you are right. Perhaps because my dataset is too large (512*512 image), it is not enough to load all of it into memory. If I want to load the dataset during each iteration, could you please provide me with some reference code? This will really be of great help to me, thank you!

**Comment by szymanowiczs** [comment]
Unfortunately I don't have any reference for this. It might be included in the coming weeks / months but I'm afraid I don't have anything that could help you right now. Best of luck!
