### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by aruiplex** [szymanowiczs/splatter-image#50]
Hi! I am reproducing your fantastic work. I am training the SRN car and SRN chair datasets.  It needs 55h in stage 1 with RTX4090+7950x. Is it normal training time-consuming? Could you please provide more information about training stage 1 and stage 2? The description in the readme is a little confusing to me and the paper is not include this part.

Thx in advance.

**Comment by szymanowiczs** [comment]
55h sounds about right, that’s 2.5 days - the paper says total for 1+2 should take around 7.

Stage 1 does most of the work, stage 2 includes the LPIPS loss which makes the reconstructions sharper, although training takes a bit longer because you need to propagate through the VGG network. Hope this helps.
