### ISSUE TITLE
Gaussian Renderer Issue

### ISSUE THREAD

**Issue by kunalkathare** [szymanowiczs/splatter-image#62]
Hi, I'm getting the following error, when trying to run eval.py on shapenet cars dataset. 
using python 3.7, torch=1.12.1, cuda11.6
installed diff-gaussian-rasterizer from gaussian splatting official repo.

Evaluating on dataset cars
Will load a model released with the paper.
Not saving any renders (only computing scores). To save renders use flag --save_vis
Loaded model!
704
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/home/test/anaconda3/envs/splatter-image/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/test/anaconda3/envs/splatter-image/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/test/anaconda3/envs/splatter-image/lib/python3.7/site-packages/lpips/weights/v0.1/vgg.pth
  0%|                                                                                                                                 | 0/704 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "eval.py", line 326, in <module>
    scores = main(dataset_name, experiment_path, 0, split=split, save_vis=save_vis, out_folder=out_folder)
  File "/home/test/anaconda3/envs/splatter-image/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "eval.py", line 287, in main
    scores = evaluate_dataset(model, dataloader, device, training_cfg, save_vis=save_vis, out_folder=out_folder)
  File "/home/test/anaconda3/envs/splatter-image/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "eval.py", line 112, in evaluate_dataset
    focals_pixels=focals_pixels_render)["render"]
  File "/data/kunal/splatter-image/gaussian_renderer/__init__.py", line 53, in render_predicted
    debug=False
TypeError: __new__() missing 1 required positional argument: 'antialiasing'

**Comment by Andrewwango** [comment]
Annoyingly due to the unstable API of `diff_gaussian_rasterizer`, some changes need to be made in `gaussian_renderer/__init__.py`:
(e.g. non-optional arg `antialiasing` introduced in [this commit](https://github.com/graphdeco-inria/diff-gaussian-rasterization/commit/9c5c2028f6fbee2be239bc4c9421ff894fe4fbe0))

You will need to add `antialiasing=True` to https://github.com/szymanowiczs/splatter-image/blob/78a6ad098e0cdc40c59c8ec98ca4fa439870fabd/gaussian_renderer/__init__.py#L41

and change https://github.com/szymanowiczs/splatter-image/blob/78a6ad098e0cdc40c59c8ec98ca4fa439870fabd/gaussian_renderer/__init__.py#L84 to `rendered_image, radii, _ = rasterizer(`

Are you still actively developing this repo to keep up with the changes @szymanowiczs ? Thanks

**Comment by RotsteinNoam** [comment]
Do the results from the paper reproduce exactly the same after applying the fixes with the new Gaussian Splatting commit? I’m unable to reproduce them, and I suspect this might be the reason.
Thanks!

**Comment by RotsteinNoam** [comment]
Just an update: The results from the paper successfully reproduce when antialiasing is set to **False**.
